CREATE TABLE `cafe_master` (
	`cafeNo` INT(11) NOT NULL AUTO_INCREMENT,
	`cafeID` VARCHAR(50) NOT NULL,
	`cafeName` VARCHAR(100) NULL DEFAULT NULL,
	`owner` VARCHAR(30) NULL DEFAULT NULL,
	`createdDate` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`cafeNo`),
	UNIQUE INDEX `cafeID` (`cafeID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
